language: c
sudo: false # only for faster builds
os: osx
osx_image: xcode9.4
script:
  - cd libft
  - make fclean
  - cd ..
  - cd real_tests
  - make test
notifications:
  email:
    recipients:
      - qvan-der@student.42.fr
    on_success: always # default: change
    on_failure: always # default: always
