# Rails launcher docker container - V1 - 05.06.2019
FROM	ft-rails:on-build

LABEL	maintainer="Quentin Van Der perre <qvan-der@42.student.fr>"

EXPOSE	3000
CMD	["rails","s","-b","0.0.0.0","-p","3000"]
